site_name: ScriptBlocks
theme:
  name: material
  logo: assets/logo.png
repo_url: https://github.com/OmgRod/ScriptBlocks-Docs

nav:
  - Home: index.md
  - Volume 1 - Getting Started:
    - Installation: vol1/installing.md
  - Volume 2 - Tutorials:
    - Creating Sprites: vol2/creating-sprites.md